### PR TITLE
Update to 1.20.1

### PR DESCRIPTION
**Pull request by Mrbysco**
`ItemEntity#getThrower` was removed so I've added an AT to be able to get the `thrower` field. 
Since the `Material` class is gone there's no easy way to fill the `overridableBlocksIdsCfg` config option so I removed it in favor of a block tag `capsule:overridable`.

### CODE REVIEW

**Comment by Lythom** [comment]
Hey ! Thanks for your contribution.
I blind merge and test the build directly. I'll come back to fixes if anything needed this week-end.

**Comment by Mrbysco** [comment]
If you uncomment the Parchment stuff you can use that too ;)

**Comment by Lythom** [comment]
Version is available at https://www.curseforge.com/minecraft/mc-mods/capsule/files?page=1&pageSize=20&version=1.20.1
I took the time to review the code, happy to discover about access transformer (didn't know that before). The modified code looks very neat: changes are clear, the build worked directly in the CI and then the built artefact in minecraft 👌. I'll bump the major version for the next release to make it clear what major version of minecraft this one refers to but it's not important for now. Also using tags instead of config for overrideable is clearly the best move.
Great work 👏!

**Comment by Mrbysco** [comment]
image
I bet that's a typo 😛

**Comment by Lythom** [comment]
@Mrbysco I got some error reported for the 1.20.1 version on capsule deploy. Are you aware of any change in 1.20 that could affect that ?
Also everything works fine on my desktop using MultiMC + forge 47.2.0, I can't reproduce so not sure what could be wrong.

The reported error:
```
[13:07:03] [Server thread/ERROR]: Couldn't deploy the capsule
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128405_(String, int)" because the return value of "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureBlockInfo.f_74677_()" is null
	at capsule.structure.CapsuleTemplate.spawnBlocksAndEntities(CapsuleTemplate.java:651) ~[Capsule-1.20.1-7.0.101.jar%23392!/:1.20.1-7.0.101]
	at capsule.StructureSaver.deploy(StructureSaver.java:329) ~[Capsule-1.20.1-7.0.101.jar%23392!/:1.20.1-7.0.101]
	at capsule.helpers.Capsule.deployCapsule(Capsule.java:139) ~[Capsule-1.20.1-7.0.101.jar%23392!/:1.20.1-7.0.101]
	at capsule.helpers.Capsule.handleItemEntityOnGround(Capsule.java:393) ~[Capsule-1.20.1-7.0.101.jar%23392!/:1.20.1-7.0.101]
```

Related line in CapsuleTemplate: 
https://github.com/Lythom/capsule/blob/a1881ed43d9445ed48c31caa7710e2979359ed19/src/main/java/capsule/structure/CapsuleTemplate.java#L651C52-L651C52

other infos I've been given :
```log
[13:03:22] [main/INFO]: ModLauncher running: args [--username, DogeKingChris, --version, forge-47.2.0, --gameDir, C:\Users\chris\curseforge\minecraft\Instances\Mhm, --assetsDir, C:\Users\chris\curseforge\minecraft\Install\assets, --assetIndex, 5, --uuid, 6a7d5e5338684e6c8822c47df5ce4bb8, --accessToken, ????????, --clientId, YTEwNDEyMDUtNmYwYS00YzE0LTk2Y2QtMWY4NGNkZGYwOGI4, --xuid, 2533274976645974, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\chris\curseforge\minecraft\Install\quickPlay\java\1700935400333.json, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[13:03:22] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 11 arch amd64 version 10.0
[13:03:23] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[13:03:23] [main/INFO]: Trying GL version 4.6
[13:03:23] [main/INFO]: Requested GL version 4.6 got version 4.6
[13:03:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/chris/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[13:03:23] [pool-2-thread-1/INFO]: GL info: AMD Radeon RX 6750 XT GL version 4.6.0 Core Profile Context 23.11.1.231020, ATI Technologies Inc.
[13:03:24] [main/INFO]: Found mod file AdChimneys-1.20.1-10.1.2.0-build.0270.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file AdFinders-1.20.1-9.1.1.0-build.0270.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file AdvancementPlaques-1.20.1-forge-1.4.10.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file AI-Improvements-1.20-0.5.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file allthetrims-3.3.5-forge+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file almostunified-forge-1.20.1-0.7.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file AmbientSounds_FORGE_v5.3.5_mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file appleskin-forge-mc1.20.1-2.5.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Aquaculture-1.20.1-2.5.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file architectury-9.1.12-forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file artifacts-forge-9.2.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file AttributeFix-Forge-1.20.1-21.0.3.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file balm-forge-1.20.1-7.1.4.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file BetterAdvancements-1.20.1-0.3.2.161.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file betterchunkloading-1.20.1-2.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file bettercombat-forge-1.8.1+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file BetterFog-1.20.1-1.2.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file betterfoliage-5.0.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file betterfpsdist-1.20.1-4.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file betterinvisibility-1.20.1-1.0.4.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file bettervillage-forge-1.20.1-3.2.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file BiomeParticleWeather-v4.1.0-1.20.1-Forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file BiomesOPlenty-1.20.1-18.0.0.592.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Bookshelf-Forge-1.20.1-20.1.6.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Bountiful-6.0.3+1.20.1-forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file caelus-forge-3.1.0+1.20.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Capsule-1.20.1-7.0.101.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file catalogue-forge-1.20.1-1.8.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file cfm-forge-1.20.1-7.0.0-pre36.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file charmofundying-forge-6.4.5+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file charms-2.0.2-1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file chefs-delight-1.0.3-forge-1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file chunksending-1.20.1-2.8.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Chunky-1.3.92.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file clickadv-1.20.1-3.6.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file cloth-config-11.1.106-forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Clumps-forge-1.20.1-12.0.0.3.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ColdSweat-2.2.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file collective-1.20.1-7.7.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file connectivity-1.20.1-4.8.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Controlling-forge-1.20.1-12.0.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file CorgiLib-forge-1.20.1-4.0.0.4.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file cosmeticarmorreworked-1.20.1-v1a.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file cpm-osc-compat-1.4.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file CrabbersDelight-1.20.1-1.1.3a.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file create-1.20.1-0.5.1.f.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file createaddition-1.20.1-1.1.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file CreativeCore_FORGE_v2.11.10_mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file creeperoverhaul-3.0.1-forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file critterfights-1.20.1-1.0.3.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ctov-3.3.6.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file cuisinedelight-1.1.11.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file cupboard-1.20.1-2.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file curios-forge-5.4.2+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file curious_armor_stands-1.20-5.0.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file CustomPlayerModels-1.20-0.6.13a.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file deeperdarker-forge-1.20.1-1.2.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Delightful-1.20.1-3.4.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Disenchanting-forge-1.20.1-2.2.4.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file DistantHorizons-2.0.0-a-1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file dummmmmmy-1.20-1.8.10.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Dungeon Crawl-1.20.1-2.3.14.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file dungeons_1.16.1_mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file dynamiclightsreforged-1.20.1_v1.6.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file dynview-1.20.1-3.9.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file EasyAnvils-v8.0.1-1.20.1-Forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file EasyMagic-v8.0.1-1.20.1-Forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file eatinganimation-1.20-5.0.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ecologics-forge-1.20.1-2.2.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file elytraslot-forge-6.3.0+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file EnchantingInfuser-v8.0.2-1.20.1-Forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file endrem_forge-5.2.3-R-1.20.X.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ends_delight-1.20.1-1.0.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file EnhancedVisuals_FORGE_v1.6.9_mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file entity_model_features_forge_1.20.1-1.1.0.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file entity_texture_features_forge_1.20.1-4.6.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file entityculling-forge-1.6.2-mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ExplorersCompass-1.20.1-1.3.3-forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file FarmersDelight-1.20.1-1.2.3.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file farsight-1.20.1-3.6.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file FastLeafDecay-31.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ferritecore-6.0.1-forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file firstperson-forge-2.2.4-mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file FpsReducer2-forge-1.20-2.5.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file framework-forge-1.20.1-0.6.16.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file friendsandfoes-forge-mc1.20.1-1.9.8.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file geckolib-forge-1.20.1-4.2.4.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file global_packs-forge-1.19.4-1.16.2_forge.jar of type MOD with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
[13:03:24] [main/INFO]: Found mod file gml-4.0.9-all.jar of type LANGPROVIDER with provider {mods folder locator at C:\Users\chris\curseforge\minecraft\Instances\Mhm\mods}
... (2 Mo restants)
```

**Comment by Mrbysco** [comment]
I'll check, if it's easier I'm also reachable on Discord (Same username)

**Comment by Mrbysco** [comment]
Should probably add some null checks because the .nbt() call on StructureTemplate can return null

**Comment by Mrbysco** [comment]
I've made 2 commits that I'm unable to PR because somehow our 1.20 branches have conflicts...
One of the commits is removing unused imports and the other adds some null checks around places where that method is directly used

**Pull request merged**
