### PR TITLE
Add Chinese Translations

### PR DESCRIPTION
**Pull request by 0nepeop1e**
language files for Simplefied Chinese (zh_CN) and Tradisional Chinese (zh_TW)

### CODE REVIEW

**Comment by Lythom** [comment]
Thank you for your contribution !
Since I can't read chinese, I won't be able to test the versions properly before release on curseforge. I'll make a prerelease build so that you can test and tell me if it's all good.

**Comment by Lythom** [comment]
[capsule-with-chinese-support.zip](https://github.com/Lythom/capsule/files/1550882/capsule-with-chinese-support.zip)

Here are the pre-release build. Can you test them in-game and tell me if it's ok ? If it's good for you I'll make the release.

**Comment by 0nepeop1e** [comment]
no problem found on all 3 versions

**Comment by Lythom** [comment]
Now merged into 1.10, 1.11, and 1.12 branches and released at https://minecraft.curseforge.com/projects/capsule/files.

Thank you for your contribution !

**Pull request closed without merging**
